version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    open-pull-requests-limit: 16
    schedule:
      interval: daily
      time: "12:00"
    pull-request-branch-name:
      separator: "-"
    labels:
      - dependencies
      - ruby
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "rails"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - ci
    open-pull-requests-limit: 2
    pull-request-branch-name:
      separator: "-"
    schedule:
      day: thursday
      interval: weekly
      time: "09:00"
