version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: monthly
      time: "09:00"
    pull-request-branch-name:
      separator: "-"
    labels:
      - dependencies
      - ruby
    allow:
      - dependency-type: "development"
    ignore:
      - dependency-name: "rails"
