detectors:
  IrresponsibleModule:
    enabled: false

  UncommunicativeMethodName:
    accept:
      - base64

  UncommunicativeVariableName:
    accept:
      - base64

directories:
  "app/helpers":
    UtilityFunction:
      enabled: false

exclude_paths:
  - db/**/*.rb
  - vendor/**/*.rb
