AllCops:
  Exclude:
    - bin/*
    - config/**/*
    - db/**/*
    - tmp/**/*

ClassLength:
  CountComments: false
  Max: 100

Documentation:
  Enabled: false

LineLength:
  Enabled: true
  Max: 79

MethodLength:
  CountComments: false
  Max: 5

ParameterLists:
  Max: 4
  CountKeywordArgs: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

TrailingWhitespace:
  Enabled: true
