AllCops:
  Exclude:
    - bin/*
    - config/**/*
    - db/**/*
    - spec/i18n_spec.rb
    - tmp/**/*

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

MethodLength:
  CountComments: false
  Max: 5

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/SymbolArray:
  Enabled: false
