require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - config/**/*
    - db/migrate/**
    - db/schema.rb
  NewCops: enable
  TargetRubyVersion: 3.2.2

Metrics/MethodLength:
  CountComments: false
  Exclude:
    - app/middleware/html_minifier.rb
    - app/uploaders/community_logo_uploader.rb
    - db/seeds/06_community.rb
  Max: 5

Layout/LineLength:
  Enabled: true
  Max: 128

Lint/UselessAssignment:
  Exclude:
    - db/seeds/contributions/**

Rails/OutputSafety:
  Exclude:
    - app/decorators/*
    - app/helpers/application_helper.rb

RSpec/AnyInstance:
  Exclude:
  - spec/controllers/contact_forms_controller_spec.rb

RSpec/ExampleLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: true
  Exclude:
    - app/models/markdown_preparator.rb

Style/SymbolArray:
  Enabled: false
