language: ruby
rvm:
  - 2.4.1
before_script:
  - psql -c 'create database fractalsoft_test' -U postgres
script:
  - RAILS_ENV=test bundle exec rails db:migrate
sudo: false
dist: trusty
addons:
  postgresql: "10"
