sudo: required
language: ruby
dist: xenial
services:
  - postgresql
before_install:
  - gem update --system
  - gem --version
install:
  - bundle install
  - npm install
rvm:
  - 2.7.2
before_script:
  - cp config/database.yml.travis config/database.yml
script:
  - RAILS_ENV=test bundle exec rails db:reset db:setup db:migrate
  - RAILS_ENV=test bundle exec rails spec
addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
    - postgresql-server-dev-11
env:
  global:
  - PGPORT=5433
  - PGUSER=travis
