sudo: required
language: ruby
dist: xenial
services:
  - postgresql
before_install:
  - gem update --system
  - gem --version
install:
  - bundle install
  - npm install
rvm:
  - 3.0.1
before_script:
  - cp config/database.yml.travis config/database.yml
script:
  - RAILS_ENV=test bundle exec rails db:reset db:setup db:migrate
  - RAILS_ENV=test bundle exec rails spec
addons:
  postgresql: "13"
  apt:
    packages:
    - postgresql-13
    - postgresql-client-13
    - postgresql-server-dev-13
env:
  global:
  - PGPORT=5433
  - PGUSER=travis
