version: '3.7'
services:
  app:
    build: .
    command: bundle exec rails s -p 3000
    env_file: .env
    environment:
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_SERVE_STATIC_FILES=true
    volumes:
      - .:/fractalsoft
    ports:
      - 3000:3000
    restart: always
    links:
      - db
    tty: true
    depends_on:
      - db

  db:
    image: "postgres:${POSTGRES_VERSION}"
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  https:
    image: abiosoft/caddy
    depends_on:
      - app
    links:
      - app
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./Caddyfile:/etc/Caddyfile

volumes:
  postgres_data:
