version: '3.9'
services:
  app:
    build: .
    env_file: .env
    environment:
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_SERVE_STATIC_FILES=true
    volumes:
      - .:/rails
    ports:
      - 3000:3000
    restart: always
    tty: true
    depends_on:
      - db

  db:
    image: "postgres:${POSTGRES_VERSION}"
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
