# fly.toml app configuration file generated
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fractalsoft-staging"
console_command = "/rails/bin/rails console"
primary_region = "ams"
swap_size_mb = 512

[env]
  RAILS_SERVE_STATIC_FILES = "1"

[build]

[deploy]
  release_command = "bundle exec rails db:migrate"
  strategy = "immediate"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
