app = "temporary-app-name"
primary_region = "ams"
console_command = "/rails/bin/rails console"

[build]

[deploy]
  release_command = "bundle exec rails db:migrate db:seed"
  strategy = "immediate"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
