default: &default
  adapter: postgresql
  encoding: utf8
  min_messages: warning
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout: 5000
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'mysecretpassword') %>

development:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB', 'fractalsoft_development') %>

test:
  <<: *default
  database: fractalsoft_test

production:
  <<: *default
  database: fractalsoft_production
