default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost

development:
  <<: *default
  database: fractalsoft_development

test: &test
  <<: *default
  database: fractalsoft_test

cucumber:
  <<: *test

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
