default: &default
  contact_email: <%= ENV['CONTACT_EMAIL'] %>
  from_email: <%= ENV['FROM_EMAIL'] %>
  mandrill_api_key: <%= ENV['MANDRILL_API_KEY'] %>
  mandrill_username: <%= ENV['MANDRILL_USERNAME'] %>

development:
  <<: *default
  secret_key_base: 93240fa2b1e1394cacdbf738427ee01a4da6b8f10275872d43a977723cd9f52278a50c2ed787eff69a88b8b0769a9e241abbd9cfb52c4a6c1d34c03e4512851e

test:
  <<: *default
  contact_email: 'test@example.com'
  from_email: 'test@example.com'
  secret_key_base: fae1fb3a6754ab8617e26e2d2d0c20df42cb36003e67ed987e8900801a588fc08abf347d2246fb78f105f93b4db53a2bd910fa6951d06e6fc45129c804d30ba5

production:
  <<: *default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
