#!/bin/bash

# This script is used to initialize git hooks.
# Run like this:
#
# $ ./script/initialize-git-hooks

cd .git/hooks
ln -s ../../scripts/githooks/post-commit
ln -s ../../scripts/githooks/pre-commit
ln -s ../../scripts/githooks/pre-push
cd ../..
