#!/bin/sh

NONE='\033[0m'
RED='\033[0;31m'
WHITE='\033[1;37m'

bundle exec scss-lint app/assets/stylesheets
if [ $? -ne 0 ]; then
  echo "${WHITE}scss-lint ${RED}failed${NONE}"
  exit 1
fi

bundle exec rubocop --fail-fast
if [ $? -ne 0 ]; then
  echo "${WHITE}rubocop ${RED}failed${NONE}"
  exit 1
fi

bundle exec fasterer
if [ $? -ne 0 ]; then
  echo "${WHITE}fasterer ${RED}failed${NONE}"
  exit 1
fi

bundle exec i18n-tasks health
if [ $? -ne 0 ]; then
  echo "${WHITE}i18n-tasks health ${RED}failed${NONE}"
  exit 1
fi

bundle exec rails_best_practices --silent
if [ $? -ne 0 ]; then
  echo "${WHITE}rails_best_practices ${RED}failed${NONE}"
  exit 1
fi

bundle exec rails zeitwerk:check
if [ $? -ne 0 ]; then
  echo "${WHITE}Zeitwerk compatibility ${RED}failed${NONE}"
  exit 1
fi

bundle exec rspec spec
if [ $? -ne 0 ]; then
  echo "${WHITE}test (rspec) ${RED}failed${NONE}"
  exit 1
fi
