name: Rails tools
on:
  pull_request:
    types: [opened,synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  i18n_tasks:
    name: I18n

    permissions:
      contents: read
      pull-requests: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: .ruby-version
      - name: Checking I18n health
        run: bundle exec i18n-tasks health

  rails_best_practices:
    name: Rails Best Practices

    permissions:
      contents: read
      pull-requests: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: .ruby-version
      - name: Checking Rails Best Practices
        run: bundle exec rails_best_practices

  zeitwerk:
    name: Zeitwerk

    permissions:
      contents: read
      pull-requests: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Download system package lists
        run: sudo apt-get update
      - name: Install system dependencies
        run: sudo apt-get install -y --no-install-recommends libvips42
        shell: bash
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: .ruby-version
      - name: Checking Zeitwerk
        run: bundle exec rails zeitwerk:check

  content_validation:
    name: Content validation

    permissions:
      contents: read
      pull-requests: read

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Download system package lists
        run: sudo apt-get update
      - name: Install system dependencies
        run: sudo apt-get install -y --no-install-recommends libvips42
        shell: bash
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: .ruby-version
      - name: Setup database
        env:
          RAILS_ENV: test
        run: |
          cp config/database.ci.yml config/database.yml
          bundle exec rails db:create
          bundle exec rails db:schema:load
          bundle exec rails db:seed
      - name: Validate content files
        env:
          RAILS_ENV: test
        run: bundle exec rails content:validate
