name: Ruby linter
on:
  pull_request:
    types: [opened,synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rubocop:
    name: Rubocop
    permissions:
      contents: read
      pull-requests: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: .ruby-version
      - name: Rubocop
        run: bundle exec rubocop --parallel
